import { useState } from 'react'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import Head from "next/head";
import Card from '../components/Card';
import Map from '../components/Map';
import Navbar from '../components/Navbar';
import Filters from '../components/Filters';
import HomeConatainer from '../components/HomeConatainer';


export default function Home({ props }) {
  console.log(props);
  return (
    <>
      <Head>
        <title>Prop-Returns</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Filters />
      <HomeConatainer props={props} />
    </>
  );
}


export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'http://localhost:4000/graphql',
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query GetHouses {
  getHouses {
    _id
    price
    address
    noOfBeds
    noOfBathroom
    area
    createdAt
    updatedAt
  }
}
    `
  });

  return {
    props: {
      props: data
    }
  }
}
